services:
  - type: web
    name: jx-horizon-backend
    env: go
    buildCommand: go build -o server ./cmd/server/main.go
    startCommand: ./server
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: "5000"
      - key: NODE_ENV
        value: production
      - key: DB_MODE
        value: production
